name: 'Terraform Defect Metrics'
description: 'Collects defect prediction metrics from Terraform code changes'
inputs:
  output_file:
    description: 'Name of the output CSV file'
    required: false
    default: 'metrics.csv'
  commit_hash:
    description: 'Specific commit hash to analyze (JIT mode)'
    required: false
  history_file:
    description: 'Path to history CSV (e.g. metrics_history.csv) for process metrics'
    required: false
outputs:
  metrics_file:
    description: 'Path to the generated metrics CSV'
    value: ${{ inputs.output_file }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mahibegoug/tf-defect-prediction-github-action:latest'
  args:
    - '--output'
    - ${{ inputs.output_file }}
    - '--commit'
    - ${{ inputs.commit_hash }}
    - '--history'
    - ${{ inputs.history_file }}
